name: env398
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip
  - numpy
  - matplotlib
  - harmonica
  - verde
  - boule
  - pooch
  - rockhound
  - gmt==6.*
  - jupyter
  - jupyterlab
  - cartopy
  - cartopy_offlinedata
  - cmocean
  - pip:
    - nbgitpuller
